# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e46d17f2205e9bb5342e0488ced0d0d5777af7e849f840675b5199a97a93f6a06726d912ba9f76ea51b784bc9a04f66c751430f46b16c4e12f2f61cad76bb15

test:
  secret_key_base: dee1874da14fd500d21112c20d94e56acfba9e627251bd43bd8a284d3c3053837f46ac30e018c8665afdcbcaa0545f4b08f464808416495b6a3e072f37e653f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
